### ISSUE TITLE
HyperGeometric Distribution cannot be found

### ISSUE THREAD

**Issue by antonkulaga** [hammerlab/math-utils#19]
The link in readme is broken and I could not find the class in sources

**Comment by ryan-williams** [comment]
[Here it is!](https://github.com/hammerlab/math-utils/blob/utils-2.2.0/utils/jvm/src/main/scala/org/hammerlab/math/HypergeometricDistribution.scala)

The README is definitely out of date; will try to give it a refresh.

btw if you don't know about github's "t" hotkey: press it on the repo's home-page and you get a fuzzy-filename-matching interface, that's how I pulled up the link above 😄

**Comment by ryan-williams** [comment]
also in case it's not clear it's in the `utils` package which is released [here](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.hammerlab.math%22%20utils)

I'll leave this open until I update the docs
